name: 'Release'

on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - 'v*'

permissions:
  contents: 'write'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b' # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup Go'
        uses: 'actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753' # ratchet:actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: 'Run GoReleaser'
        uses: 'goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7' # ratchet:goreleaser/goreleaser-action@v4
        with:
          distribution: 'goreleaser'
          version: 'v1.18.2'
          args: 'release --clean'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
